#! /bin/sh

# pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          5
# bspc config top_padding         20
# bspc config bottom_padding         0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer false
# bspc config click_to_focus none

bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^3'
bspc rule -a Firefox desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Border
bspc config focused_border_color        "#535d6c"
bspc config normal_border_color         "#222222"
bspc config active_border_color         "#535d6c"

# Autostart
#
~/.config/bspwm/autorun.sh

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
