#!/usr/bin/env bash

# if [ "$#" -lt "1" ]; then
#   echo "Provide a least one direction"
#   exit 1
# fi

DIRECTION="internal_monitor"

if [ "$#" -gt "0" ]; then
  DIRECTION=$1
fi

if [ "$DIRECTION" == "monitor_left_align_left" ]; then

  if [[ $(xrandr -q | grep 'DP1 connected') ]]; then
    bspc wm -O DP1 LVDS1
    bspc monitor DP1 -d 1 2 3 4 5 6
    bspc monitor LVDS1 -d 7 8 9 10
  fi

elif [ "$DIRECTION" == "monitor_left_align_right" ]; then

  if [[ $(xrandr -q | grep 'DP1 connected') ]]; then
    bspc wm -O LVDS1 DP1
    bspc monitor LVDS1 -d 1 2 3 4 5 6
    bspc monitor DP1 -d 7 8 9 10
  fi

else 
    # bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8 9 10
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

