#!/bin/bash

# EPISODE_PATH="/mnt/nfs/mnt/coisas/series/[AnimeRG] Naruto Shippuden (Complete Series 001-500) Naruto Shippuuden [720p] [HEVC] [x265] [Batch] [pseudo]/Season 08 (Episodes 152-175)"
EPISODE_PATH="/mnt/nfs/mnt/coisas/series/[AnimeRG] Naruto Shippuden (Complete Series 001-500) Naruto Shippuuden [720p] [HEVC] [x265] [Batch] [pseudo]"

if [ -f $HOME/.config/dmenu/dmenurc ]; then
  . $HOME/.config/dmenu/dmenurc
else
  DMENU='dmenu -i'
fi

cd "$EPISODE_PATH"

# choice=$(\ls "$EPISODE_PATH" | sed -n -e "/mkv$/p" | $DMENU -l 30)
choice=$(find * -type f | sed -n -e "/mkv$/p" | $DMENU -l 30)

if [ -z "$choice" ]; then
	echo "Exit Esc"
	exit
fi

# mpv "$EPISODE_PATH/$choice" --start=00:01:30
# mpv "$EPISODE_PATH/$choice" 
mpv "$choice" 
