#!/usr/bin/env bash

if [ -f $HOME/.config/dmenu/dmenurc ]; then
  . $HOME/.config/dmenu/dmenurc
fi

[ ! -f "/usr/share/doc/pass/examples/dmenu/passmenu" ] && exit 1

/usr/share/doc/pass/examples/dmenu/passmenu -i $THEME -l 30 -p "pass saved credentials: "
