#!/usr/bin/env bash

if [ ! -z $WAYLAND_DISPLAY ]; then
    DMENU='rofi -dmenu -i'
elif [ -f $HOME/.config/dmenu/dmenurc ]; then
  . $HOME/.config/dmenu/dmenurc
else
  DMENU='dmenu -i'
fi

declare -a options=(" hibernate 
 suspend 
 reboot 
 shutdown 
 quit ")

echo -e "${options[@]}" 
echo $DEMNU

choice=$(echo -e "${options[@]}" | $DMENU -p 'Choose System Operation: ')


if [ "$choice" == ' quit ' ]; then
    echo "Program terminated."
    exit
fi

if [ -z "$choice" ]; then
    echo "Exit Esc"
    exit
fi

if [ "$choice" == ' suspend ' ]; then
    command="systemctl suspend"
fi
if [ "$choice" == ' hibernate ' ]; then
    command="systemctl hibernate"
fi
if [ "$choice" == ' reboot ' ]; then
    command="systemctl reboot"
fi
if [ "$choice" == ' shutdown ' ]; then
    command="systemctl poweroff"
fi

exec $command

