#!/bin/bash
editor=nvim

if [ -f $HOME/.config/dmenu/dmenurc ]; then
  . $HOME/.config/dmenu/dmenurc
else
  DMENU='dmenu -i'
fi

declare -a options=(" awesome 
 i3 
 sxhkd 
 nvim 
 zsh 
 qutepage 
 edit-files 
 quit ")

choice=$(echo -e "${options[@]}" | $DMENU -p 'Edit a config file: ')

if [ "$choice" == ' quit ' ]; then
    echo "Program terminated."
    exit
fi

if [ -z "$choice" ]; then
      echo "Exit Esc"
      exit
fi

if [ "$choice" == ' awesome ' ]; then
    command="$HOME/.config/awesome/"
fi
if [ "$choice" == ' bash ' ]; then
    command="$HOME/.bashrc"
fi
if [ "$choice" == ' i3 ' ]; then
    command="$HOME/.config/i3/config"
fi
if [ "$choice" == ' sxhkd ' ]; then
    command="$HOME/.config/sxhkd/sxhkdrc"
fi
if [ "$choice" == ' xmonad ' ]; then
    command="$HOME/.xmonad/xmonad.hs"
fi
if [ "$choice" == ' zsh ' ]; then
    command="$HOME/.zshrc"
fi
if [ "$choice" == ' nvim ' ]; then
    command="$HOME/.config/nvim"
fi
if [ "$choice" == ' edit-files ' ]; then
    command="$HOME/.config/dmenu/dmenu-edit-configs.sh"
fi
if [ "$choice" == ' qutepage ' ]; then
    command="$HOME/.config/qutebrowser/startup.html"
fi

# Wezterm
exec default_terminal -e $editor $command
# Others
# exec default_terminal -e "$editor $command"
