#!/usr/bin/env bash

if [ -f $HOME/.config/dmenu/dmenurc ]; then
  . $HOME/.config/dmenu/dmenurc
fi

PASSMENU_ARGS="-i $THEME -l 30 -p 'pass saved credentials: '"

if [ -f "/usr/share/doc/pass/examples/dmenu/passmenu" ]; then
    /usr/share/doc/pass/examples/dmenu/passmenu -i $THEME -l 30 -p 'pass saved credentials: '
elif [ -f "$(which passmenu)" ]; then
    passmenu -i $THEME -l 30 -p 'pass saved credentials: '
else
    exit 1
fi
