term xterm-256color
confirm_os_window_close 0
update_check_interval 0
shell_integration disabled

scrollback_lines 5000
clipboard_control write-clipboard write-primary no-append

# Visual feedback
enable_audio_bell no
bell_on_tab no
window_alert_on_bell no

include theme.conf
