# Default font size
font_size 10.5

# Cursor settings
cursor #ffffff
cursor_text_color background
cursor_shape block
cursor_blink_interval -1
cursor_stop_blinking_after 15.0

# Color scheme

background #1f1f1f
foreground #ffffff

# Selection
selection_foreground none
selection_background #2f2f2f

# include hack_nerd_font.conf
include iosevka.conf
include tokyonight_night.conf

window_padding_width 5
