#!/bin/bash

BAT=$(acpi -b | grep -E -o '[0-9][0-9]?%')

# Full and short texts
echo "BAT: $BAT"
echo "BAT: $BAT"

# Set urgent flag below 5% or use orange below 20%
[ ${BAT%?} -le 5 ] && exit 33
[ ${BAT%?} -le 20 ] && echo "#FF8000"
[ ${BAT%?} -le 50 ] && [ ${BAT%?} -gt 20 ] && echo "#FFA500"
[ ${BAT%?} -gt 50 ] && echo "#7EC485"

exit 0
