Net/ThemeName "Arc-Dark"
Net/IconThemeName "Delft-Amber-Dark"
Gtk/DecorationLayout "menu:minimize,maximize,close"
Gtk/FontName "Cantarell 11"
Gtk/MonospaceFontName "Fira Mono 10"
Gtk/CursorThemeName "Adwaita"
Xft/Antialias 1
Xft/Hinting 0
Xft/HintStyle "hintnone"
# Xft/DPI 90000 
Xft/DPI 90000 
