#Net/ThemeName "Mint-Y-Dark"
Net/ThemeName "Arc-Dark"
Net/IconThemeName "Mint-L-Teal"
Gtk/DecorationLayout "menu:minimize,maximize,close"
#Gtk/FontName "Source Code Pro 10"
Gtk/FontName "Ubuntu Regular 10"
Gtk/MonospaceFontName "Source Code Pro 10"
# Gtk/CursorThemeName "Bibata-Modern-Classic"
Gtk/CursorThemeName "DMZ-White"
# Xft/Antialias 1
# Xft/Hinting 0
# Xft/HintStyle "hintnone"
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/Antialias 1
Xft/RGBA "rgb"
# Xft/DPI 90000 
Xft/DPI 105000 
