#!/usr/bin/env bash

if [ -f "$HOME/.config/aliasrc" ]; then
    . "$HOME/.config/aliasrc"
fi

if [ -d "$HOME/.config/profile.d" ]; then
	for i in "$HOME/.config/profile.d/*.sh"; do
		if [ -r $i ]; then
			. $i
		fi
	done
	unset i
fi
