#!/usr/bin/env bash

COINS=(
  "DOGE 21.22913"
  "XRP 8.6481"
  "WBTC 0.00016"
  "ATOM 0.27819"
  "EOS 1.4642"
)

for coin in "${COINS[@]}"; do
    read coin qtd <<< "$coin"  # uses default whitespace IFS
    echo $coin": "$(curl -s "https://eur.rate.sx/$qtd$coin")
done

## OLD IMPLEMENTATION
# SYMBOL1="DOGE"
# QUANT1="21.22913"
# SYMBOL2="BAT"
# QUANT2="12.28631"
# SYMBOL3="WBTC"
# QUANT3="0.00016"
# SYMBOL4="ATOM"
# QUANT4="0.27819"
# # SYMBOL2="SOL"
# # QUANT2="0.21725"

# echo $SYMBOL1": "$(curl -s "https://eur.rate.sx/$QUANT1$SYMBOL1")
# echo $SYMBOL2": "$(curl -s "https://eur.rate.sx/$QUANT2$SYMBOL2")
# echo $SYMBOL3": "$(curl -s "https://eur.rate.sx/$QUANT3$SYMBOL3")
# echo $SYMBOL4": "$(curl -s "https://eur.rate.sx/$QUANT4$SYMBOL4")

