#!/bin/bash

xautolock -time 10 -locker "betterlockscreen -l dim" -detectsleep &
## Killer features suspend after lock
# xautolock -time 10 -locker "betterlockscreen -l dim" -killtime 20 -killer "systemctl suspend" -detectsleep &
