#!/bin/bash
killall trayer &> /dev/null
trayer --edge top --align right --widthtype request --padding 4 --SetDockType true --SetPartialStrut true --expand true --monitor 1 --transparent true --alpha 0 --tint 0x222222  --height 18 &
