#!/bin/bash

OUTPUT_SOURCE=$(pactl list | grep "Monitor Source" | awk '{print $3}')
cvlc -vvv pulse://alsa_output.pci-0000_00_1b.0.analog-stereo.monitor --sout '#transcode{acodec=mp3,ab=128,channels=2}:standard{access=http,dst=0.0.0.0:8888/pc.mp3}'
