#!/bin/bash

OUTPUT_SOURCE=$(pactl list | grep "Monitor Source" | awk '{print $3}')
echo "Starting stream for $OUTPUT_SOURCE)"

sleep 5

cvlc -vvv pulse://$OUTPUT_SOURCE --sout \
  '#transcode{acodec=mp3,ab=128,channels=2}:standard{access=http,dst=0.0.0.0:8887/pc.mp3}'
