#!/bin/bash
# /usr/bin/i3exit

if [ -f "$HOME/.config/i3/lock.sh" ]; then
  lockScreen="$HOME/.config/i3/lock.sh"
fi

# with openrc use loginctl
if [[ $(cat /proc/1/comm) == "systemd" ]]; then
  logind=systemctl 
else 
  logind=loginctl
fi

case "$1" in
    lock)
        $lockScreen
        ;;
    logout)
        i3-msg exit
        ;;
    switch_user)
        dm-tool switch-to-greeter
        ;;
    suspend)
        $lockScreen && $logind suspend
        ;;
    hibernate)
        $lockScreen && $logind hibernate
        ;;
    reboot)
        $logind reboot
        ;;
    shutdown)
        $logind poweroff
        ;;
    *)
        echo "== ! i3exit: missing or invalid argument ! =="
        echo "Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
        exit 2
esac

exit 0
